apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-id
  labels:
    app: project-id
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-id
  template:
    metadata:
      labels:
        app: project-id
    spec:
      containers:
      - name: project-id
        image: niginx
        ports:
        - containerPort: 80
